modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/never-enough-candy/issues"
license="LGPL v2.1 (Textures ARR)"

[[mods]]
modId="neverenoughcandy"
updateJSONURL="https://updates.blamejared.com/get?n=neverenoughcandy&gv=1.16.5"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.neverenoughcandy]]
    modId="forge"
    mandatory=true
    versionRange="[36,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.neverenoughcandy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.neverenoughcandy]]
    modId="bookshelf"
    mandatory=true
    versionRange="[10,)"
    ordering="AFTER"
    side="BOTH"